# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Nuevo_nido
                                 A QGIS plugin
 Este pluggin generara un zona de influencia al posicionamiento colibri esmeralda
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-04-22
        copyright            : (C) 2021 by Carlos Antonio Archaga Martinez
        email                : caarchaga@unah.hn
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Nuevo_nido class from file Nuevo_nido.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .nuevo_nido import Nuevo_nido
    return Nuevo_nido(iface)
